parameters:
  task: false
  extension: false

jobs:
- ${{ if eq(parameters.task, true) }}:
  - job: ${{ variables.taskName }}
    pool:
      name: Default
    workspace:
      clean: all
    variables:
    - template: variables.yml
    steps:
    - template: steps/build.yml
      parameters:
        name: ${{ variables.taskName }}
        path: ${{ variables.tasksPath }}
        restore: true
        build: true
        test: true
        clean: true
        publish: true

- ${{ if eq(parameters.extension, true) }}:
  - job: Extension
    pool:
      name: Default
    workspace:
      clean: all
    variables:
    - template: variables.yml
    dependsOn:
    - ${{ if eq(parameters.task, true) }}:
      - ${{ variables.taskName }}
    steps:
    - template: steps/package.yml
      parameters:
        path: ${{ variables.artifactsPath }}
        contents: |
          Images/**
          LICENSE
          *.md
          *.json
        version: ${{ variables.extensionVersion }}
        publish: true
