
parameters:
  path: ""
  output: ""

steps:
- task: DeleteFiles@1
  displayName: Clean artifact
  inputs:
    contents: |
      CI
      TaggerV1/**/*.ts
      TaggerV1/ts*.json
      TaggerV1/tests
    removeDotFiles: true

- task: TfxInstaller@3
  displayName: Install TFX CLI

- task: PackageAzureDevOpsExtension@3
  displayName: Package extension
  inputs:
    rootFolder: ${{ parameters.path }}
    outputVariable: ${{ parameters.output }}
