parameters:
  path: ""
  version: ""
  output: ""

steps:
- task: TfxInstaller@3
  displayName: Install TFX CLI

- task: DeleteFiles@1
  displayName: Clean extension
  inputs:
    contents: |
      .git
      .vscode
      .gitignore
      CI
      TaggerV1/.eslintrc
      TaggerV1/ts*.json
      TaggerV1/tests

- task: PowerShell@2
  displayName: Version extension
  inputs:
    targetType: filePath
    filePath: CI/scripts/version.ps1
    arguments: >
      -Path ${{ parameters.path }}
      -Patch ${{ parameters.version }}
      -UpdateBuildNumber
    pwsh: true

- task: PackageAzureDevOpsExtension@3
  displayName: Package extension
  inputs:
    rootFolder: ${{ parameters.path }}
    ${{ if ne(parameters.output, '') }}:
      outputVariable: ${{ parameters.output }}
