trigger:
  branches:
    include:
    - master

pool:
  name: Default

workspace:
  clean: all

steps:
- template: templates/build.yml
  parameters:
    path: TaggerV1
    restore: true
    lint: true
    build: true
    test: true
    clean: true

- template: templates/package.yml
  parameters:
    path: $(Build.SourcesDirectory)

- publish: $(extensionPath)
  displayName: Publish artifact
  artifact: Extension

- publish: $(Build.SourcesDirectory)/TaggerV1
  displayName: Publish artifact
  artifact: Task
